services:
  openclaw-init:
    image:  ghcr.io/ider-zh/openclaw-docker:main
    build: .
    env_file:
      - .env
    volumes:
      - ./openclaw:/home/node/.openclaw:z
      - ./bootstrap:/bootstrap
    command: bash /bootstrap/extensions_init.sh

  openclaw:
    image:  ghcr.io/ider-zh/openclaw-docker:main
    build: .
    env_file:
      - .env
    volumes:
      - ./openclaw:/home/node/.openclaw:z
    depends_on:
      openclaw-init:
        condition: service_completed_successfully  
    command: openclaw gateway
    restart: unless-stopped
    # ports:
    #   - "18789:18789"